config/routes.rb
FamilyGame::Application.routes.draw do
  devise_for :students

  root :to => "students#index"

  devise_for :users
  

  resources :points_spents

  resources :rewards

  resources :points do
    collection do
      post :multiple
    end
  end
  

  resources :activities

  resources :users

  resources :students

end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :activity_id, :xp_earned, :student_id, :comment
  belongs_to :student
  belongs_to :activity
  validates_presence_of :activity_id, :student_id, :xp_earned

  after_save :update_xp
  after_update :update_xp
  after_destroy :update_xp

  def update_xp
  	student.update_xp
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user_or_student

  helper_method :sort_column, :sort_direction
  
  # GET /points
  # GET /points.json
  def index
    @points = Point.order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new
    @activities = Activity.where("active = ?", true)

    @student = Student.find(params[:student_id]) if params[:student_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.json
  def create
      @point = Point.new(params[:point])

      # Set point.xp_earned based on the activity chosen
      @activity = Activity.find(params[:point][:activity_id])
      @point.xp_earned = @activity.activity_xp

      respond_to do |format|
        if @point.save
          flash[:success] = 'Points added successfully'
          format.html  { redirect_to new_point_path(student_id: params[:point][:student_id]) }
          format.json { render json: @point, status: :created, location: @point }
        else
          format.html { render action: "new" }
          format.json { render json: @point.errors, status: :unprocessable_entity }
        end
      end
  end

  def multiple
    @activity_ids = params[:point][:activity_id]
    @activity_ids.each do |activity_id|
      unless activity_id.blank?
        params[:point][:activity_id] = activity_id

        @point = Point.new(params[:point])

        # Set point.xp_earned based on the activity chosen
        @activity = Activity.find(activity_id)

        @point.xp_earned = @activity.activity_xp
        if !@point.save
          flash[:error] = 'Failed to add points.'
        else
          flash[:success] = 'Added points.'
        end   
      end
    end
    respond_to do |format|
      format.html { redirect_to student_path(params[:point][:student_id]) }
      format.json { render json: @point, status: :created, location: @point }
    end
  end

  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      flash[:error] = 'Points deleted successfully'
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Student.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  # def authenticate_user_or_student
  #   if current_student
  #     authenticate_student!
  #   else
  #     authenticate_user!
  #   end
  # end

end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= simple_form_for @point, url: multiple_points_path, method: :post, html: {class: "form-horizontal"} do |f| %>
  <div class="field">
    <% if params[:student_id] %>
      <h4>Add points for <%= @student.username %></h4>
      <%= f.hidden_field :student_id, value: params[:student_id] %>
    <% else %>
      <%= f.association :student, label_method: :username, :selected => params[:student] %><br />
    <% end %>
  </div>
  <div class="field">
    <%= f.association :activity, label_method: :name, as: :check_boxes, collection: @activities, :selected => params[:activity] %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Add Points Now', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/points/_form_multiple.html.erb
<%= simple_form_for @point, url: multiple_points_path, method: :post, html: {class: "form-horizontal"} do |f| %>
  <div class="field">
    <% if params[:student_id] %>
      <h4>Add points for <%= @student.username %></h4>
      <%= f.hidden_field :student_id, value: params[:student_id] %>
    <% else %>
      <%= f.association :student, label_method: :username, :selected => params[:student] %><br />
    <% end %>
  </div>
  <div class="field">
    <%= f.association :activity, label_method: :name, as: :check_boxes, collection: @activities, :selected => params[:activity] %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Add Points Now', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Points Earned</h1>

<table class="table table-striped table-condensed" >
  <tr>
    <th>Username</th>
    <th>Activity</th>
    <th><%= sortable "xp_earned", "Points" %><i class = 'icon-resize-vertical'></i></th>
    <th><%= sortable "created_at", "Date Earned" %><i class = 'icon-resize-vertical'></i></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @points.each do |point| %>
  <% if point.student.user.id == current_user.id %>
    <tr>
      <td><%= point.student.username %></td>
      <td><%= point.activity.name %></td>
      <td><%= point.xp_earned %></td>
      <td><%= point.created_at.strftime("%b-%d-%Y") %></td>
      <td><%= link_to 'Show', point %></td>
      <td><%= link_to 'Edit', edit_point_path(point) %></td>
      <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<p><%= link_to 'Add Points', new_point_path, class: 'btn' %></p>

app/views/points/new.html.erb
<h1>Add Points</h1>

<%= render 'form' %>

<% if current_student %>
	<%= link_to 'View Player', current_student, class: 'btn' %>
<% else %>
	<%= link_to 'View Player', student_path(params[:student_id]), class: 'btn' %>
<% end %>

app/views/points/show.html.erb
<p>
  <b>User:</b>
  <%= @point.user_id %>
</p>

<p>
  <b>Activity:</b>
  <%= @point.activity_id %>
</p>

<p>
  <b>Points:</b>
  <%= @point.xp %>
</p>


<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>