config/routes.rb
FamilyGame::Application.routes.draw do
  devise_for :students

  root :to => "students#index"

  devise_for :users
  

  resources :points_spents

  resources :rewards

  resources :points do
    collection do
      post :multiple
    end
  end
  

  resources :activities

  resources :users

  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  attr_accessible :xp_gained, :xp_used, :xp_current, :user_id
  attr_accessible :login
  attr_accessor :login

  belongs_to :user
  has_many :points, dependent: :destroy
  has_many :points_spents, dependent: :destroy

  def update_xp
    xp_total = points.sum(:xp_earned)
    xp_spent_total = points_spents.sum(:xp_spent)
    update_column(:xp_gained, xp_total)
    update_column(:xp_current, xp_total - xp_spent_total)
  end

  def update_xp_used
    xp_total = points.sum(:xp_earned)
    xp_spent_total = points_spents.sum(:xp_spent)
    update_column(:xp_used, xp_spent_total)
    update_column(:xp_current, xp_total - xp_spent_total)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user_or_student

  # allow acces to these functions in the view using helper_method
  helper_method :sort_column, :sort_direction

  # GET /students
  # GET /students.json
  def index
    @students = Student.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /studens/1
  # GET /studens/1.json
  def show
    @student = Student.find(params[:id])
    @points_feed = Point.where("student_id  = ? AND updated_at > ?", @student.id, 1.days.ago ).order('created_at desc').limit('20')
    @points_spent_feed = PointsSpent.where("student_id  = ? AND updated_at > ?", @student.id, 7.days.ago ).order('created_at desc').limit('20')

    # Create list of activities that have not been done in the last 24 hours
    @todo = Activity.all
    @points_feed.each do |activity_completed|
      @todo.reject!{ |act| act.id == activity_completed.activity_id}
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
    # unless current_student.id == @student.id
    #   flash[:error] = 'You can not edit selected student.'
    #   redirect_to students_path
    # end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])
    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end


  private

  # def authenticate_user_or_student
  #   if current_student
  #     authenticate_student!
  #   else
  #     authenticate_user!
  #   end
  # end

  # def authorize_student
  #   @student = student.find(params[:id])
  #   unless current_user.admin? || current_student.id == @student.id
  #     flash[:error] = 'You can not edit selected student.'
  #     redirect_to students_path
  #   end
  # end

  def sort_column
    Student.column_names.include?(params[:sort]) ? params[:sort] : "username"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
    <%= f.input :username %>
    <% if current_user && current_user.id > 0 %>
	    <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id } %>
    <% end %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.button :submit, "Save Player", class: "btn btn-success" %>
<% end %>

app/views/students/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/students/index.html.erb
<h1>Players</h1>

<table class="table table-striped table-condensed" >
  <tr>
    <th><%= sortable "username", "Username" %></th>
    <th><%= sortable "xp_current", "Current Points" %></th>
    <th><%= sortable "xp_gained", "Total Earned" %></th>
    <th><%= sortable "xp_used", "Total Spent" %></th>
    <th><%= "Parent" %></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.username %></td>
    <td><%= student.xp_current %></td>
    <td><%= student.xp_gained %></td>
    <td><%= student.xp_used %></td>
    <td><%= student.user.username %></td>
    <td>
      <% if (current_student && student.id == current_student.id) || (current_user && current_user.admin?) %>
        <%= link_to 'Show', student, class: 'btn btn-primary btn-small' %> 
        <%= link_to 'Edit', edit_student_path(student), class: 'btn btn-small' %>
      <% end %>
      <% if current_user && current_user.admin? %>
        <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />
<p>
  <% if current_user && current_user.admin? %>
    <%= link_to 'New Player', new_student_path, class: 'btn btn-success' %>
  <% end %>
</p>

app/views/students/new.html.erb
<h1>New Player for <%= current_user.username %></h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/students/show.html.erb
<div class="hero-unit">
  	<h1><%= @student.username %></h1>
  	<br />
  	<% if @student.last_sign_in_at %>
	  	<p>Last Login <%= time_ago_in_words(@student.last_sign_in_at) %> ago</p>
	<% else %>
		Player has not logged in yet
	<% end %>
  	<div class="progress" style="width: 100%; height:1.5em;">
		<div class="bar bar-success" style="width: 100%;">Total Earned: <%= @student.xp_gained %> pts</div>
	</div>
  	<div class="progress" style="width: 100%; height:1.5em;">
		<div class="bar bar-info" style="width: <%= (@student.xp_gained - @student.xp_used) * 100.0 / @student.xp_gained %>%;">Remaining: <%= @student.xp_gained - @student.xp_used %> pts</div>
		<div class="bar bar-danger" style="width: <%= 100.0 - (@student.xp_gained - @student.xp_used) * 100.0 / @student.xp_gained %>%;">Total Spent: <%= @student.xp_used %> pts</div>
	</div>
	<%= link_to 'Add Points', new_point_path(student_id: params[:id]), class: 'btn' %> 
	<%= link_to 'Spend Points', new_points_spent_path(student_id: params[:id]), class: 'btn' %>
</div>

<div class="row">
	<div class="span4">
		<div class="well">
			<h4>Pts Earned in Last 24 hrs</h4>
			<% @points_feed.each do |point|%>
			<p>
				<%= point.activity.name %> (<%= point.activity.activity_xp %>)
		        <%= link_to '', point, method: :delete, data: { confirm: 'Are you sure you want to delete these points?' }, class: 'icon-trash' %><br /> -- <em style="font-size:80%;"><%= time_ago_in_words(point.updated_at) %> ago</em>
			</p>
			<% end %>
		</div>
	</div>
	<div class="span4">
		<div class="well">
			<h4>Things To Do Today</h4>
			<% @todo.each do |todo|%>
			<p>
				<%= todo.name %> (<%= todo.activity_xp %>)<br />
			</p>
			<% end %>
		</div>
	</div>
	<div class="span4">
		<div class="well">
			<h4>Pts Spent in Last 7 Days</h4>

			<% @points_spent_feed.each do |points_spent|%>
			<p>
				<%= points_spent.reward.name %> (<%= points_spent.reward.xp_cost %>)<br /> -- <em style="font-size:80%;"><%= time_ago_in_words(points_spent.updated_at) %> ago</em>
			</p>
			<% end %>
		</div>
	</div>
</div>