config/routes.rb
FamilyGame::Application.routes.draw do
  devise_for :students

  root :to => "students#index"

  devise_for :users
  

  resources :points_spents

  resources :rewards

  resources :points do
    collection do
      post :multiple
    end
  end
  

  resources :activities

  resources :users

  resources :students

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :name
  has_many :students
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  attr_accessible :login


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user, only: :edit

  # allow acces to these functions in the view using helper_method
  helper_method :sort_column, :sort_direction

  # GET /users
  # GET /users.json
  def index
    @users = User.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @students = Student.where("user_id = ?", @user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    # unless current_user.role == "Admin" || current_user.id == @user.id
    #   flash[:error] = 'You can not edit selected user.'
    #   redirect_to users_path
    # end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def authorize_user
    @user = User.find(params[:id])
    unless current_user.admin? || current_user.id == @user.id
      flash[:error] = 'You can not edit selected user.'
      redirect_to users_path
    end
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%# f.input :admin %>
    <%= f.button :submit, class: "m-btn" %>
<% end %>

app/views/users/index.html.erb
<h1>Parents</h1>

<table class="table table-striped table-condensed" >
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Admin</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    <td>
        <%= link_to 'Show', user, class: 'btn btn-primary btn-small' %> 
        <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-small' %>
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<p>
  <%= link_to 'New Parent', new_user_path, class: 'btn btn-success' %>
</p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
	<b>Username:</b>
	<%= @user.username %>
</p>

<p>
	<b>Email:</b>
	<%= @user.email %>
</p>

<p>
	<b>Admin:</b>
	<%= @user.admin %>
</p>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-small' %>
<hr>
<% if current_user && current_user.id == @user.id %>
<h4>Players</h4>
<table class="table table-striped table-condensed" >
	<tr>
		<th>Username</th>
		<th>Current Points</th>
		<th>Total Earned</th>
		<th>Total Spent</th>
		<th></th>
	</tr>

	<% @students.each do |student| %>
	<tr>
		<td><%= student.username %></td>
		<td><%= student.xp_current %></td>
		<td><%= student.xp_gained %></td>
		<td><%= student.xp_used %></td>
		<td>
			<%= link_to 'Show', student, class: 'btn btn-primary btn-small' %> 
			<%= link_to 'Edit', edit_student_path(student), class: 'btn btn-small' %>
			<%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
		</td>
	</tr>
	<% end %>
</table>
<%= link_to "Manage Earnings", points_path, class: 'btn btn-primary' %>
<%= link_to "Manage Spending", points_spents_path, class: 'btn btn-primary' %>
<%= link_to "New Player", new_student_path, class: 'btn btn-success' %>
<% end %>
<br />
<br />