config/routes.rb
FamilyGame::Application.routes.draw do
  devise_for :students

  root :to => "students#index"

  devise_for :users
  

  resources :points_spents

  resources :rewards

  resources :points do
    collection do
      post :multiple
    end
  end
  

  resources :activities

  resources :users

  resources :students

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shah Family Game</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <ul class="nav pull-right ul-padding">
<!--
             <% if current_user %>
              <li class='dropdown'>
                <a class='dropdown-toggle' data-toggle="dropdown" href="#">Parents<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Manage Earnings", points_path %></li>
                  <li> <%= link_to "Manage Spending", points_spents_path %></li>
                </ul>
            <% end %>
 --> 
            <li><%= link_to "Leaderboard", students_path %></li>
            <li><%= link_to "Activities", activities_path %></li>
            <li><%= link_to "Rewards", rewards_path %></li>
            <% if user_signed_in? %>
              <li class='dropdown'>
                <a class='dropdown-toggle' data-toggle="dropdown" href="#">
                  <%= current_user.username %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%# link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
                  <li><%= link_to "Profile", user_path(current_user)%></li>
                  <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                  </li>
                </ul>
            <% elsif student_signed_in? %>
              <li class='dropdown'>
                <a class='dropdown-toggle' data-toggle="dropdown" href="#">
                  <%= current_student.username %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_student_registration_path(current_student)%></li>
                  <li><%= link_to "Edit User", edit_student_path(current_student)%></li>
                  <li> <%= link_to "Logout", destroy_student_session_path, :method => :delete %>
                  </li>
                </ul>
            <% else %>
              <li class='dropdown'>
                <a class='dropdown-toggle' data-toggle="dropdown" href="#">Login<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to('Login Parent', new_user_session_path)  %></li>
                  <li><%= link_to('Login Player', new_student_session_path)  %></li>
                  </li>
                </ul>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
              <% end %>
      				<%= yield %>
              <%= debug(params) if Rails.env.development? %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
</body>
</html>